package org.robloxjava.transpiler.luau;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * The class in charge of the actual luau source.
 */
public class LuauWriter {
    private String luauSource;

    public LuauWriter() {
        luauSource = "-- Generated by roblox-java v0.0.0.\n";
    }

    public void write(String text) {
        luauSource += text;
    }

    public void writeLine(String line) {
        luauSource += STR."\{line}\n";
    }

    public String getLuauSource() {
        return luauSource;
    }


    // static utils

    public static String separateListCommas(List<String> strings) {
        StringBuilder ret = new StringBuilder();

        for (String p : strings)
            ret.append(Objects.equals(p, strings.getLast()) ? p : STR."\{p}, ");

        return ret.toString();
    }
}
