-- Generated by roblox-java v0.0.0.
local Java = require(game:GetService("ReplicatedStorage").__java.RuntimeLib)
-- ▼ Class definition 'Animal' ▼
local Animal = {}
do
	Animal.__index = Animal
	function Animal.__tostring()
		return "Animal"
	end
	function Animal.constructor(name, age, specialInfo)
		local self = setmetatable({}, Animal)
		self.name = name
		self.age = age
		self.specialInfo = specialInfo
		return self
	end
	function Animal:getName()
		return self.name
	end
	function Animal:getAge()
		return self.age
	end
	function Animal:getSpecialInfo()
		return self.specialInfo
	end
	function Animal:setSpecialInfo(newInfo)
		self.specialInfo = newInfo
	end
	Animal.__className = "Animal"
end
-- ▲ Class definition 'Animal' ▲
-- ▼ Class definition 'Program' ▼
local Program = {}
do
	Program.__index = Program
	function Program.__tostring()
		return "Program"
	end
	function Program.constructor()
		local self = setmetatable({}, Program)
		return self
	end
	function Program.main(args)
		local x = Animal.constructor("Barkson", 4, {5, 7, 9, "poopies"})
		local y = {}
		x:setSpecialInfo({1, 2, 3, true})
	end
	Program.__className = "Program"
end
-- ▲ Class definition 'Program' ▲
Program.main({}) -- ◀ Internal testing mode ◀
