-- Generated by roblox-java v0.0.0.
-- ▼ Class definition 'Animal' ▼
local Animal = {}
do
	Animal.__index = Animal
	function Animal.__tostring()
		return "Animal"
	end
	function Animal.constructor(stringA, x)
		local self = setmetatable({}, Animal)
		local screwYou = stringA
		return self
	end
	function Animal:getSomeThing()
		return 6
	end
	function Animal.part2(korblox)
		return 8
	end
	function Animal:ara()
		return nil
	end
end
-- ▲ Class definition 'Animal' ▲
-- ▼ Class definition 'Program' ▼
local Program = {}
do
	Program.__index = Program
	function Program.__tostring()
		return "Program"
	end
	function Program.constructor()
		local self = setmetatable({}, Program)
		return self
	end
	function Program.hi()
		return 999
	end
	function Program.main(args)
		local y = 800
		local rrr = nil
		local someOtherAnimal = Animal.constructor("a", 5)
		someOtherAnimal = nil
		local arara = Animal.constructor("Screw you!", 2)
		local x = 3 + y / arara:getSomeThing()
		Animal.part2("Hello, world!")
		local theResultOfHi = Program.hi()
	end
end
-- ▲ Class definition 'Program' ▲
